Revert "feat: yaml linting (#18)"
This reverts commit 4842ea072a0ec6e7f8762521691cf2eea8595cb3.
This formatting applied during this causes failures in Azure-Pipelines

diff --git a/steps/python/python.build.yml b/steps/python/python.build.yml
--- a/steps/python/python.build.yml
+++ b/steps/python/python.build.yml
@@ -2,46 +2,46 @@
 #
 # Build, lint and test Python modules based on setuptools (setup.py)
 #
----
+
 steps:
-  - task: UsePythonVersion@0
-    inputs:
-      versionSpec: $(python.version)
-      architecture: "x64"
+- task: UsePythonVersion@0
+  inputs:
+    versionSpec: $(python.version)
+    architecture: "x64"
 
-  - bash: |
-      if [ ! -f requirements_dev.txt ]; then
-        echo "ERROR: no requirements_dev.txt available in project!"
-        exit 1
-      fi
-      pip install --user --no-cache-dir -r requirements_dev.txt
-    displayName: "Install build & test prerequisites"
+- bash: |
+    if [ ! -f requirements_dev.txt ]; then
+      echo "ERROR: no requirements_dev.txt available in project!"
+      exit 1
+    fi
+    pip install --user --no-cache-dir -r requirements_dev.txt
+  displayName: "Install build & test prerequisites"
 
-  - script: python setup.py build
-    displayName: "Build"
+- script: python setup.py build
+  displayName: "Build"
 
-  - script: |
-      python setup.py install --user
-      python setup.py lint --lint-output-format parseable
-    condition: eq(variables['Agent.OS'], 'Linux')
-    displayName: "Pylint"
+- script: |
+    python setup.py install --user
+    python setup.py lint --lint-output-format parseable
+  condition: eq(variables['Agent.OS'], 'Linux')
+  displayName: "Pylint"
 
-  - script: |
-      python setup.py test --addopts "--cov-report xml:build/coverage.xml --cov-report term --cov-branch --junitxml=build/test_results.xml"
-    displayName: "Tests"
+- script: |
+    python setup.py test --addopts "--cov-report xml:build/coverage.xml --cov-report term --cov-branch --junitxml=build/test_results.xml"
+  displayName: "Tests"
 
-  - script: |
-      python setup.py install --user
-      python setup.py build_sphinx
-    displayName: "Docs"
+- script: |
+    python setup.py install --user
+    python setup.py build_sphinx
+  displayName: "Docs"
 
-  - task: PublishTestResults@2
-    condition: succeededOrFailed()
-    inputs:
+- task: PublishTestResults@2
+  condition: succeededOrFailed()
+  inputs:
       testResultsFiles: "**/test*.xml"
       testRunTitle: "$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)]"
 
-  - task: PublishCodeCoverageResults@1
-    inputs:
+- task: PublishCodeCoverageResults@1
+  inputs:
       codeCoverageTool: Cobertura
       summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
